# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    robot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robot_arm_controller:
  ros__parameters:
    joints:
      - base_cima_to_base_link
      - braco1_to_base_cima
      - braco2_to_braco1
      - braco3_to_braco2
      - garra_base_to braco3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity